<a href="https://colab.research.google.com/github/SaiShivam/Pycaret/blob/master/TorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized

In [ ]:
x = torch.empty(1) # scalar
print(x)

tensor([5.2384e-09])


In [ ]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[5.2384e-09, 3.0716e-41, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [ ]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[5.2383e-09, 3.0716e-41, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.4602, 0.4168, 0.4214],
        [0.7087, 0.4958, 0.1543],
        [0.3908, 0.6223, 0.6982],
        [0.5653, 0.3848, 0.9364],
        [0.2811, 0.1069, 0.7932]])


In [ ]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# check size
print(x.size())

torch.Size([5, 3])


In [ ]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [ ]:
# check type
print(x.dtype)

torch.float16


In [ ]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [ ]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

In [ ]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [ ]:
# elementwise addition
z = x + y
# torch.add(x,y)

In [ ]:

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

In [ ]:
# substraction
z = x - y
z = torch.sub(x, y)

In [ ]:
# multiplication
z = x * y
z = torch.mul(x,y)

In [ ]:
# division
z = x / y
z = torch.div(x,y)

In [ ]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.1271, 0.5358, 0.3445],
        [0.7621, 0.5163, 0.5919],
        [0.9748, 0.0735, 0.1327],
        [0.6679, 0.9284, 0.7219],
        [0.5662, 0.4239, 0.1776]])
tensor([0.1271, 0.7621, 0.9748, 0.6679, 0.5662])
tensor([0.7621, 0.5163, 0.5919])
tensor(0.5163)


In [ ]:

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.5163143873214722


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:

# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:

# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# again be careful when modifying
a += 1
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:

# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()